## /boot/extlinux/extlinux.conf
default l0
menu title U-Boot menu
prompt 0
timeout 10
label l0
	menu label ImmortalWrt A5E 6.6.98-1-aw2607 (diag shell)
	linux /boot/vmlinuz-6.6.98-1-aw2607
	initrd /boot/initrd.img-6.6.98-1-aw2607
	fdtdir /usr/lib/linux-image-6.6.98-1-aw2607/
	append root=UUID=4739022d-153d-4199-bc4b-35ab086fcddb console=ttyAS0,115200n8 earlyprintk=sunxi-uart,0x2500000 rootwait clk_ignore_unused mac_addr=${mac} mac1_addr=${mac1} loglevel=4 rw earlycon consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0
